# version: "3.8"

services:
  bot:
    build: .
    image: ghcr.io/indoomni/omnioom-whatsapp
    container_name: omnioom-whatsapp_${PROXY_APP_NAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./auth_info:/app/auth_info
      - ./logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROXY_APP_NAME}.rule=Host(`${PROXY_HOSTNAME}`)"
      - "traefik.http.routers.${PROXY_APP_NAME}.entrypoints=https"
      - "traefik.http.routers.${PROXY_APP_NAME}.tls=true"
      - "traefik.http.routers.${PROXY_APP_NAME}.service=${PROXY_APP_NAME}"
      - "traefik.http.services.${PROXY_APP_NAME}.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
